### ISSUE TITLE
No shade button shown for groups

### ISSUE THREAD

**Issue by Paddler21** [HomeAutoUser/SD_Keeloq__old_Jaro#13]
For groups there is no 'shade' button shown, it is explicitly disabled in the code. Although I think it makes sense to disable the 'learn' button there is well good use of 'shade' for groups, like for all window blinds on the same sun facing side.

```1202c1202
<                       $html.= SD_Keeloq_attr2htmlButtons($grpInfo[1], $name, $ShowIcons, 0, 0);
---
>                       $html.= SD_Keeloq_attr2htmlButtons($grpInfo[1], $name, $ShowIcons, $ShowShade, 0);```

**Comment by HomeAutoUser** [comment]
Hallo, 
Thanks, i will see in code.

**Comment by HomeAutoUser** [comment]
Hello @Paddler21,

please load current code from
https://github.com/HomeAutoUser/SD_Keeloq__old_Jaro
and test it. With positive feedback I take this in SIGNALduino dev-r34.
Thanks

**Comment by Paddler21** [comment]
Funktioniert, danke!
