### ISSUE TITLE
Gruppensteuerung ab dem 10. Motor funktioniert nicht.

### ISSUE THREAD

**Issue by Hungry67** [HomeAutoUser/SD_Keeloq__old_Jaro#14]
Ich habe 16 Motoren.
Wenn ich versuche, Motoren per Gruppensteuerung ab dem 10. Motor zu steuern, so 
fahren diese Motoren nicht.

Beispiel: DG:10,11 =kein Motor fährt
oder
Alle:1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16 =Motoren 1-9 fahren, Motoren 10-16 fahren nicht.

**Comment by HomeAutoUser** [comment]
@Hungry67 danke für den Hinweis, wir schauen es uns an.

**Comment by HomeAutoUser** [comment]
@Hungry67 wie sendest du diese Gruppensteuerung oder anders formuliert, wie ist deine Vorgehensweise?

**Comment by HomeAutoUser** [comment]
@Hungry67 bitte lade dir mal das gefixte Modul hier 
https://github.com/HomeAutoUser/SD_Keeloq__old_Jaro 
herunter und teste bitte. Bei positiver Rückmeldung übernehme ich es in das SIGNALduino dev.

**Comment by Paddler21** [comment]
addGroups OGhinten:3,4,10
Jetzt läuft auch die 10 mit, funktioniert.

**Comment by HomeAutoUser** [comment]
Perfekt :)

**Comment by Hungry67** [comment]
Danke!!!
