### ISSUE TITLE
ChannelAttribute Check

### ISSUE THREAD

**Issue by HomeAutoUser** [HomeAutoUser/SD_Keeloq__old_Jaro#17]
Ich habe mal soeben beim testen, alle 16 Channels eingestellt.
Bei Änderung auf wenigere Channels werden die "mehr" Channels nicht gelöscht.

Wie denkt Ihr darüber, wenn wir die Readings da prüfen würden und welche "größer dem ChannelsAttributWert" sind, zu löschen?

Müssen die alten drin bleiben?

**Comment by bismosa** [comment]
Kann man machen...aber überflüssige readings lösche ich auch gerne selber...so wird mir die Arbeit abgenommen :)

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
Du weißt wie dies geht, aber kann man das dem unerfahrenem User zumuten?
Ich sehe es als Erleichterung und dies führt auch nicht zu Irretation wenn man ein User ein List machen würde nach Aufforderung weil man Fehler sucht.

**Comment by meier81** [comment]
Finde die Idee auch gut, lösche zwar meine nicht mehr benötigten Readings auch händisch wenn sie nicht automatisch gelöscht werden, aber vom Komfort und vor allem für Anfänger wäre das eigentlich eine gute Idee.

**Comment by HomeAutoUser** [comment]
Diese Option wurde nun mit in die Version integriert und somit schließe ich den Faden. Bei Problemen oder Anregungen, einfach Reopen oder einen neuen Faden eröffenen.
