### ISSUE TITLE
Shade ohne Funktion

### ISSUE THREAD

**Issue by Hugo3340** [HomeAutoUser/SD_Keeloq__old_Jaro#9]
Hi zusammen,

ich hatte bislang, das Modul von den Bastbudenbuben im Einsatz, bislang funktionierte das Anfahren der dritten Position (Shade) ohne Probleme. Vor kurzem bin ich auf das neue Modul (CUL) umgestiegen (14_SD-Jaro). Leider funktioniert seitdem die shade funktion nicht mehr. Hat von euch jemand einen Tip oder eine Hilfestellung? Des Weiteren versuche ich das ASC anzulegen, leider komme ich hier ebenfalls nicht weiter und die Rollos reagieren nicht.
Vielen Dank.

Gruß 
Hugo

**Comment by HomeAutoUser** [comment]
Hallo Hugo,
Nutzt du das aktuelle Modul?

Hier https://github.com/HomeAutoUser/Jaro ist der Link beschrieben weil es nicht mehr SD-Jaro heißt.

Teste bitte mit diesem weil dort einiges zum alten Modul angepasst wurde und in der commandref beschrieben ist.

Mfg

**Comment by Hugo3340** [comment]
Hi HomeAutoUser,
vielen Dank für Deine schnelle Antwort.
Ich habe nun das Modul aktualisiert. Das Einlernen der ShadePosition funktioniert, leider bewegt sich der Motor bei betätigen des Shade nicht.
Hast du noch eine Idee?
mfg

**Comment by bismosa** [comment]
Hallo!

@HomeAutoUser 
Hat shade überhaupt schon Mal bei jemandem funktioniert? Will nicht ausschließen das wir da vielleicht noch einen Fehler drin haben

@Hugo3340 
Ich bin leider unterwegs und kann es nicht nachlesen. Was muss normalerweise auf der FB gedrückt werden damit die shade-pos. angefahren wird?
Dann probiere Mal den gleichen Code als Tastenkombination...

Gruß
Bismosa

**Comment by Hugo3340** [comment]
Hi,
die Ansteuerung gemäß Hersteller (ca 5sek Stop gedrückt halten).
Wenn ich den Code von Shade=0100 (Stop) ändere, dann fährt die Rollade diese Shade Position an.
Da ich jedoch 10 Rolläden habe, wird für einen gewissen Zeitraum, diese Funktion geblockt - heißt ich kann nicht von oben nach unten, sämtliche Rollos kurzfristig über den Shade Button anfahren. Das hat jedoch bei dem alten Modul, von den Bastelbudenbuben funktioniert.
Brauche auch noch etwas Hilfe, wie ich ASC anlege und dann die Rollos nach belieben ansteuern kann.

Vielen Dank.

Gruss
Hugo

**Comment by bismosa** [comment]
Hallo!
Sorry...ich komme gerade nicht ganz mit...

- Wo änderst du den Code auf shade?
- Was ist ASC?

Sehe ich es richtig, das es einzeln immer funktioniert? Also nach ein paar tastendrücken erst das System ins Stocken gerät?
Das könnte daran liegen, das zu viele Nachrichten verschickt werden. Dann muss ein Funk-Stick das senden pausieren. Sonst gibt es mecker mit den Nachbarn und der Bundesnetzagentur.
Wenn du eh alle gleichzeitig fahren möchtest benutze bitte die Gruppenfunktion.

Gruß
Bismosa

**Comment by Hugo3340** [comment]
Hi,
wenn ich in der Keeloq Datei den Shade code von 0110 auf einen Stop ändere 0100, wird das Rollo 20x mit Stop angesteuert. Dann fährt das Rollo in Shade Position, ich muss dann jedoch etwas warten bevor ich das nächste Rollo mit Shade ansteuere. 
Funktioniert die Shade Positionen der Jarolift Motoren bei Dir ohne Änderung des Codes?
ASC ist AutoShuttersControl. 

Gruss
Hugo

**Comment by bismosa** [comment]
Hallo!
Das kann ich mir erst nächste Woche in Ruhe anschauen, warum 20x gesendet wird und warum der Code falsch ist....
Nach 20x senden wundert es mich nicht das die Funkzeit dann abgelaufen ist.

Meine Rolläden unterstützen keinen Shade...daher konnte ich das nie testen.

Zu ASC kann ich nichts sagen. Ich benutze das ROLLO Modul. Das klappt super. Ich denke das sollte aber damit auch problemlos gehen...sonst bitte im FHEM Forum beim Modulprogrammierer melden.

Gruß
Bismosa

**Comment by bismosa** [comment]
Hallo!
Ich habe mir das gerade nochmal genauer angesehen...
20x wird gesendet, da die STOP-Taste ja 5 sek. gedrückt werden muss. Das geht wohl leider nicht anders. Das kostet dann wirklich viel Funkzeit...also wenn mehrere gesteuert werden sollen bitte Gruppenfunktionen benutzen.

@HomeAutoUser 
Weißt Du noch woher der Code "0101" für shade kam? Ich habe gerade das hier wiedergefunden:
https://github.com/HomeAutoUser/Jaro/issues/1#issuecomment-462071150
Hier hatten wir das auch schon (aber vermutlich durch die anderen Sachen das wieder vergessen :) ).
Wenn ich das richtig sehe, dann können wir den Shade-Befehl (lange Stop) auch gar nicht empfangen?

@gandi1791 @Ralf9 @meier81
Hat jemand von euch Rolläden mit der shade-Funktion im Einsatz? Funktioniert das bisher bei euch?

Gruß
Bismosa

**Comment by Hugo3340** [comment]
Guten Morgen,
Vielen Dank für die schnelle Rückmeldung und den Einsatz. Bei dem alten Model von den Bastelbudenbuben 98_Jatolift.pm - Version 0.5, hat die Shade Funktion ohne Problem funktioniert. Hier funktionierte auch eine deutlich schnellere Ansteuerung - wie diese das Realisiert haben kann ich leider nicht entziffern. 

Gruss Hugo

**Comment by bismosa** [comment]
Hallo!
Was meinst Du genau mit "schnellere Ansteuerung"? Das Du jeden einzelnen in Shade direkt nacheinander fahren konntest? Oder die Zeit bis ein Rolladen sich in Bewegung setzt?

Gruß
Bismosa

**Comment by Hugo3340** [comment]
Guten Morgen,
Das ich jedes Rollo, direkt nacheinander fahren kann - ohne Probleme und zu warten.

**Comment by bismosa** [comment]
Hallo!

Den Fall kann ich Dir erklären. Schau mal hier:
https://wiki.fhem.de/wiki/1%25_Regel

Der Sketch von Bastelbudenbuben und auch der Dongle von https://github.com/madmartin/Jarolift_MQTT sowie die Fernbedienungen von Jarolift
kümmern sich nicht um diese Regel. Sollten sich aber Nachbarn mal beschweren, das ihre Funkthermometer nichts mehr anzeigen oder andere Nachbarn sich beschweren, das bei denen z.B. das Garagentor zu bestimmten Zeiten nicht mehr funktioniert kann es u.U. sehr viel Ärger geben.
Daher wurde dies in den CUL-Sticks permanent umgesetzt, das die max. Funkzeit nicht überschritten werden kann.
Da es leider keine eigene Taste für den Shade-Befehl gibt (sondern wirklich 5sek. lang das gleiche gesendet wird) wird diese Zeit sehr schnell überschritten.

Warum machst Du Dir nicht einfach eine oder mehrere Gruppen...dann brauchst du nur einen Knopf betätigen und alle Rolläden fahren gleichzeitig los... :)
Geht ganz einfach...schau einfach kurz in die Device Help...dort ist erklärt, wie die Gruppen angelegt werden.

Gruß
Bismosa

**Comment by Hugo3340** [comment]
Hi Bismosa,
Ok, das könnte sein - jedoch muss ich sagen, das die aktuelle Lösung 20x Stop, wohl eher die Sendezeit überschreiten könnte. Es muss doch einen Code geben, mit dem die Shade Position direkt angefahren werden kann. Du hast ja schon die aktuelle Anmerkung mit dem Code 0101 gemacht - irgendwie muss dieser entstanden sein. 

Mfg
Hugo

**Comment by bismosa** [comment]
Hallo!
Der Code 0101 war völliger Müll. Da du ja Rolläden mit Shade-Funktion hast...du könntest ja Mal durchprobieren....ändere im Modul denn Code für eine Taste (z.b. Hoch) und probiere was passiert (nach einem reload). Vielleicht gibt es ja noch einen unbekannten Code :) 
Dann kannst du hier ja Mal eine Aufstellung machen, was bei welchem Code passiert :)
So viele Möglichkeiten gibt es ja nicht...

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
Hallo, ich denke du kommst besser weg, wenn du alle Tasten einfach nacheinander drückst und schaust ob der Status passt.

Solltest du eine Fernbedienung besitzen die die Funktion shade unterstützt, so muss diese auch erläutert sein und letztendlich musst du nur das machen und den Code / die Nachricht uns geben um es nachvollziehen zu können.

:)

**Comment by gandi1791** [comment]
> @gandi1791 @Ralf9 @meier81
> Hat jemand von euch Rolläden mit der shade-Funktion im Einsatz? Funktioniert das bisher bei euch?

Tut mir Leid, ich habe keine Motoren/Rollladen mit Shadefunktion.

**Comment by Paddler21** [comment]
Shade hat bei mir auch nicht funktioniert, tut aber jetzt einwandfrei nach Änderung des Codes auf 0100 (im models hash). Bei mir genügen 12 repeats, damit ergibt sich eine Signallänge von etwas über einer Sekunde.

**Comment by HomeAutoUser** [comment]
Danke für den Hinweis.
Wir werden es Schritt für Schritt mit einarbeiten.
Die kleinen Baustellen häufen sich, so möchte ich erst mal Schritt für Schritt vorgehen.

**Comment by HomeAutoUser** [comment]
Hallo,

@Paddler21, meinst du diesen Code
															`"shade"				=>	"0101", # 20x stop	(stop with 20x repeats)`

welchen du abgeändert hast?

Mich macht stutzig, das wir damals hier 
https://github.com/HomeAutoUser/SD_Keeloq__old_Jaro/issues/1#issuecomment-462071150

andere Werte zusammengetragen hatten und du praktisch den shade Code mit Stop versehen würdest.

Gibt es vielleicht unterschiedliche Versionen der Hardware? Können wir mal die Codes alles zusammentragen wenn jeder bei sich mal die Tasten drücken würde?

MfG

**Comment by bismosa** [comment]
Hallo,
Stop ist richtig. Das war damals ein Fehler von mir.
Shade wird nur durch langes drücken der Stop Taste aktiviert. Es gibt keine extra Taste dafür.

Gruß
Bismosa

**Comment by bismosa** [comment]
Wenn es mit 12 zuverlässig funktioniert dann sollten wir das so übernehmen. Oder @HomeAutoUser  ?

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
Mit der Aussage von euch beiden, würde ich den Code anpassen und somit dann

`"shade"				=>	"0101", # 20x stop	(stop with 20x repeats)`

auf 

`"shade"				=>	"0100", # 20x stop	(stop with 20x repeats)`

setzen damit wir hier ebenso einen Haken setzen können :-)

**Comment by Hugo3340** [comment]
Hi,
vielen Dank erstmal an alle, für die Tatkräftige Unterstützung. 
Was mich an dieser Methode jedoch stört ist, das ich dann fast 2sek bis zum nächsten Befehl warten muss. Die Bastelbudenbuben, hatten eine elegantere Lösung gehabt - ich könnte ich die Shade Positionen, wie ein Maschinengewehr ansteuern. 
Aktuell habe ich mir eine Alternative geschaffen - in dem ich in Rollo, die Shade Position auf 80 abgeändert habe. 
Jedoch muss es auch noch eine andere Möglichkeit geben oder?

Gruss 
Hugo3340

**Comment by HomeAutoUser** [comment]
Hallo @Hugo3340,

ich habe die Rolloos zwar nicht aber ich kann dir erkären wieso du 2 Sekunden warten musst :-)

1) Ein Funkbefehl dauert eben so lange wenn dieser Wiederholt wird.
2) Die Rollos interprätieren das shade eben nur mit mehrfach Stop oder du hast eine andere Hardware

Bastelbudenbuben, elegantere Lösung? Die Umsetzung mit dem Modul kann man leider nicht vergleichen. Wie war denn dort das Verhalten?

**Comment by Hugo3340** [comment]
Einmal definiert und dann ansteuern. Hier klappte in dieser Richtung ohne Wartezeiten.

**Comment by Paddler21** [comment]
Definieren geht hier genauso mit 4x Stop. Die Signal-/Wartezeit muss doch so lange sein, wie das Drücken der Stop Taste auf der Fernbedienung mindestens dauern muss.

**Comment by HomeAutoUser** [comment]
Weil das Thema Shade, Sendewiederholungen auch gerade hier https://github.com/RFD-FHEM/RFFHEM/issues/632#issuecomment-526765758 angesprochen wurde und mit der Anzahl von 4 bestätigt wurde, so würde ich bitte hier mitlesenden User bitten, mal einen Test zu fahren sofern sie die Rolladen besitzen.

Wir haben 2 Varianten,
1) Code auf fest 4 Wiederholungen zu setzen ohne Rücksicht auf Verluste
2) ein attribut zu ergänzen weil man davon ausgehen kann, das es vermutlich 2 Hardwarevarianten gibt. Nicht ohne Grund hat damals der Bastelbudenbuben Sketch fest den Wert von 20 verankert

**Comment by HomeAutoUser** [comment]
Hallo,
mit der Änderung 

`"shade" => "0101", # 20x stop (stop with 20x repeats)`

auf

`"shade" => "0100", # 20x stop (stop with 20x repeats)`

gibt es Probleme! Wenn Ihr nun die Taste Stop drückt, erhaltet Ihr den Zustand shade in FHEM.
Hier müssen wir alle einen Weg finden aber das ganze müssen wir struktieriert angehen.

Jeder der die Funktion Shade unterstützt muss mir der Fernbedienung alle Tasten druchprobieren.
Passend dazu bitte

```
Gerät / Gerätebeziechung:
Hersteller / Fabrikat:
Kaufdatum:
getestete Funktion:
Modulversion: (aktuell das Datum in der zweiten Zeile des Modules)
```

Wenn wir das nicht zusammen strukturiert bewältigen, so haben wir einen Haufen wo wir uns gegenseitig die Schuld geben oder immer sagen werden, meins geht, meins geht nicht ;-)

**Comment by bismosa** [comment]
Wenn ich mich da aus der Entfernung kurz einmischen darf...
Shade wird bei allen Rolläden die dies unterstützen nur durch das lange drücken der Stop-taste gefahren.
Die Zeit mit 20x Stop kommt glaube ich von dem MadMartin Version. 
Das es mit 4x stop funktioniert wag ich zu bezweifeln...dann würde man dies doch ständig versehentlich starten?
Es gibt nach meinem Kenntnisstand keine unterschiedlichen Versionen!

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
@bismosa in die Ferne :-)

Hier die Fakten, das shade auch mit 4x Stop existiert (noch warme Infos) ... Okay 5x
Die Aufzeichnung erfolge nach Tastendruck Shade an einer TDRC 01W
```
Shade:		CC1101_RSSI 94	serialnumber: 0x02558800 // function code: 0x04 // disc: 0x00 devicekey low:   // high:   // decoded: 0x010002fe
		CC1101_RSSI 94	serialnumber: 0x02558800 // function code: 0x04 // disc: 0x00 devicekey low:   // high:   // decoded: 0x010002fe
		CC1101_RSSI 94	serialnumber: 0x02558800 // function code: 0x04 // disc: 0x00 devicekey low:   // high:   // decoded: 0x010002fe
		CC1101_RSSI 94	serialnumber: 0x02558800 // function code: 0x04 // disc: 0x00 devicekey low:   // high:   // decoded: 0x010002fe
		CC1101_RSSI 94  serialnumber: 0x02558800 // function code: 0x04 // disc: 0x00 devicekey low:   // high:   // decoded: 0x010002fe
```

**Comment by bismosa** [comment]
@Paddler21 
Kannst du Mal bitte probieren wo bei dir das Minimum liegt?
Geht da auch weniger als 12?

@banabas
Hast du auch schonmal das senden probiert?

@HomeAutoUser 
Der Log könnte ggf. Evtl nicht ganz vollständig sein. Ich hatte das damals auch häufiger, das nicht jeder einzelne Befehl (beim lange drücken) geloggt wurde...

Gruß
Bismosa

**Comment by Hungry67** [comment]
Meine Motoren stammen von 2012.
Ich habe mit der Version von Bastelbuden damals den Shadepunkt gesetzt.
Mit der Version hier, habe ich es einfach übernommen und es funktioniert problemlos.
Alle Shadepunkte der Motoren werden angefahren.
Etwas warten muss ich dabei schon aber eine Verzögerung hatte ich auch der der Bastelbudenversion.

**Comment by Hugo3340** [comment]
Hi,
gemäß der Hersteller Anweisung, muss für das anfahren der Shade Position, an der Fernbedienung die Stop Taste für 5sek gedrückt werden.

**Comment by HomeAutoUser** [comment]
Ich habe eine Vermutung nachdem ich mir nun alle Fakten und Codes mal angesehen habe.

Es wäre nun von Vorteil, wenn jeder der Funktion Shade via FHEM probiert, wenn die Tasten wie im orginal defineirt sind

```
"JaroLift" =>	{	Button => { "up"	=>	"1000",	# button
"stop"		=>	"0100",	# button - for learn (LearnVersion new, step 2)
"down"		=>	"0010",	# button
"learn"		=>	"0001",	# function - old LearnVersion
"shade"		=>	"0101", # function - 20x stop	(stop with 20x repeats) mod to 15 repeats after test | old 0101 | other user 0100 ?
			# manual - button Stop push 5 seconds (2012)
															"shade_learn"	=>	"",			# function -  4x stop	(stop 4x push)
"updown"	=>	"1010"	# buttons together - for learn (LearnVersion new, step 1)
```

ich vermute, so geht die Funktion shade via FHEM set nicht.
Danach macht Ihr mal diesen Test nochmal aber mit

```
"shade"		=>	"0100", # function - 20x stop	(stop with 20x repeats) mod to 15 repeats after 
```

Diese Erkenntnisse teilt Ihr mit bitte mit. Nach diesem Fakt, gehen wir shade_learn durch.
Der Fehler liegt dort, das wenn Ihr Shade 0100 nutzt und das funktioniert beim senden, Ihr beim Empfang eines Stop Befehles immer Shade im State bekommt ;-) Testet mal bitte und für die Codeanpassung bin ich ja da.

**Comment by Hugo3340** [comment]
Die Shadefunktion, klappt nur mit dem Code 0100 - mindestens 15 wiederholungen. Shade Lernfunktion 4xStop. Sämtliche andere Code Möglichkeiten funktionieren nicht.

**Comment by HomeAutoUser** [comment]
@Hugo3340, genau das habe ich erwartet.
Nun lässt du mal im Code bitte
```
"JaroLift" =>	{	Button => { "up"	=>	"1000",	# button
"stop"		=>	"0100",	# button - for learn (LearnVersion new, step 2)
"down"		=>	"0010",	# button
"learn"		=>	"0001",	# function - old LearnVersion
"shade"		=>	"0101", # function - 20x stop	(stop with 20x repeats) mod to 15 repeats after test | old 0101 | other user 0100 ?
			# manual - button Stop push 5 seconds (2012)
															"shade_learn"	=>	"",			# function -  4x stop	(stop 4x push)
"updown"	=>	"1010"	# buttons together - for learn (LearnVersion new, step 1)
```

und suchst du dir diese Position (Zeile 457)
```
$button = $cmd;
$buttonbits = $models{$model}{Button}{$cmd};
```
dort ersetzt du mal bitte 
```
$buttonbits = $models{$model}{Button}{$cmd};
```
durch
```
$buttonbits = $models{$model}{Button}{$cmd} if ($cmd ne "shade");
$buttonbits = $models{$model}{Button}{stop} if ($cmd eq "shade"); ### fix for Status shade - need usertests! https://github.com/HomeAutoUser/SD_Keeloq__old_Jaro/issues/9#issuecomment-526834923
```
und wiederholst den Test.
Es sollte nun shade gehen und auch stop / hoch / runter.
shade_learn ist später dran.

**Comment by Paddler21** [comment]
Repeats 10 gingen bei mir nicht, 12 gehen einwandfrei.

**Comment by HomeAutoUser** [comment]
Hallo, habt ihr mal versucht einen Test zu fahren wie hier https://github.com/HomeAutoUser/SD_Keeloq__old_Jaro/issues/9#issuecomment-526836244 von mir beschrieben? Ich denke nun zu wissen wieso wir für shade einen uns nicht bekannten Code nutzen. Deswegen bitte unbedingt mal testen. Wenn ihr shade und stop gleich definiert, kommt es zu Fehlermeldungen beim Empfang.

**Comment by Hugo3340** [comment]
Hi,
ich habe es getestet und kann aktuell sagen das die Funktion gegeben ist. Es ist etwas besser geworden, jedoch muss ich weiterhin ca 3sek warten, bevor ich das nächste Rollo mit der Shade funktion ansteuere. Die Led vom stick, hat sonst ca 8sek geblinkt, jetzt blinkt diese nur einmal. 
Gruss
Hugo3340

**Comment by Hungry67** [comment]
Habe den Patch eingepflegt.
Shade ging vorher und nachher.
Was ich aber vorher hatte, dass beim Drücken von Stop auf einem Handsender (TDRC 16)
shade angezeigt wurde, was ja nicht richtig ist.
Nach einspielen der Patches wird beim Empfang receive stop group control wenn Gruppe über FB angewählt
und receive stop on single control wenn Einkanal an der FB ausgewählt wurde.
Also so wie es sein sollte!

**Comment by HomeAutoUser** [comment]
Danke für das Feedback. Ich werde heute Abend den Patch einspielen das jeder ihn via Update erhält :)

Wir müssten vielleicht mal die shade_learn testen ob das geht.

@Hugo3340 , ich werde nochmal das Signal berechnen und schauen ob da was machbar ist zwecks ansprechbarkeit nacheinander.

**Comment by HomeAutoUser** [comment]
Hallo 
> 
> Es ist etwas besser geworden, jedoch muss ich weiterhin ca 3sek warten, bevor ich das nächste Rollo mit der Shade funktion ansteuere. Die Led vom stick, hat sonst ca 8sek geblinkt, jetzt blinkt diese nur einmal.
> Gruss
> Hugo3340

Ich habe nun noch einmal nachgesehen und gerechnet.
Bei der derzeitigen Programmierung sind 15 Wiederhollungen drin beim Kommando Shade. Daraus ergibt sich eine reine Sendezeit von ca. 1,8 Sekunden. Schneller geht es auf jedenfall nicht umzusetzen. Es kann natürlich sein, das du die Repeats noch auf 20 hast? Diese wurden ja verringert auf 15.

Hast du ggf. das Attribut LearnVersion gesetzt? Von der Codeumsetzung ergibt sich deine gefühlte Zeit nur, wenn du die LernVersion New ausgewählt hast und das Kommando learn absendest. so kommst du auf eine ca. Zeit von 4 Sekunden.

MfG

**Comment by HomeAutoUser** [comment]
In der jetzigen Version haben wir das Problem Shade gefixt und so würde ich aus Übersichtlichkeit den Faden schließen. Wenn jemand expliziet noch Probleme damit hat, bitte den Faden Reopen oder einen neuen eröffnen. So behalte ich hier besser den Überblick was für fixes noch offen sind oder behoben wurden.
